export const MOVIES_FETCH_LOADING = "MOVIES_FETCH_LOADING";
export const MOVIES_FETCH_FAIL = "MOVIES_FETCH_FAIL";
export const MOVIES_FETCH_SUCCESS = "MOVIES_FETCH_SUCCESS";
export const FILTER_MOVIES='FILTER_MOVIES'

export const TOGGLE_NAV='TOGGLE_NAV'

export const FETCH_OFFLINE_MOVIES='FETCH_OFFLINE_MOVIES'
export const ADD_MOVIE_LOADING='ADD_MOVIE_LOADING'
export const ADD_MOVIE_SUCCESS='ADD_MOVIE_SUCCESS'
export const ADD_MOVIE_FAIL='ADD_MOVIE_FAIL'

export const GET_GENRES='GET_GENRES'
export const GET_SELECTED_GENRE='GET_SELECTED_GENRE'
export const SET_SELECTED_GENRE='SET_SELECTED_GENRE'